### PR TITLE
Feature/navigation

### PR DESCRIPTION
**Pull request by samrosecruz**
@riacataquian @victorsolis  halp. i cant seem to load my JS. got this error:
```
Cannot find module "phoenix_html" from "web/static/js/app"require
```

also, see my change for brunch config if there's something wrong with it

### CODE REVIEW

**Comment by riacataquian** [comment]
@samrosecruz cant still figure it out. :<

**Comment by samrosecruz** [comment]
@riacataquian G. lag gif but it has a slide animation when clicking the icon

nav

**Comment by samrosecruz** [comment]
wait lang pala. found a bug

**Comment by samrosecruz** [comment]
oks. G fo realz

**Comment by riacataquian** [comment]
Thank you @samrosecruz! 💛

**Pull request merged**
