### PR TITLE
styles join section

### PR DESCRIPTION
**Pull request by samrosecruz**
@riacataquian halp. i cant load ionicons lol

### CODE REVIEW

**Comment by riacataquian** [comment]
@samrosecruz whatz happeningz? Have you tried this na? Sa loob ng `plugins: {}` in your `brunch-config.js`. 
```    sass: {
      options: {
        includePaths: [
          "node_modules/ionicons/scss"
        ]
      }
    }
```

Then import mo sa `app.scss` mo: `@import 'ionicons';`

**Comment by samrosecruz** [comment]
sige i'll try, what i did was `@import 'node_modules/ionicons/dist/scss/ionicons';`

**Comment by samrosecruz** [comment]
Update:

alchemist

**Comment by samrosecruz** [comment]
Ok, weird, so importing it to `app.css` wont work but importing it to a separate scss file will.

Aaaaaaand it loads the wrong icon per class hahaha sample:
screen shot 2016-05-24 at 11 26 06 pm

**Comment by victorsolis** [comment]
wat

**Comment by riacataquian** [comment]
Thanks, yay! :yellow_heart:

**Pull request merged**
